spring:
  application:
    name: zuul-gateway-api
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: https://localhost:8761/eureka
zuul:
  routes:
    book-service:
      url: http://localhost:8081/api/v1/booksbooks/**