spring:
  application:
    name: api-gateway
#  cloud:
#    gateway:
#      routes:
#        - id: book-service
#          uri: lb://book-service
#          predicates: Path=/api/v1/books
#        - id: book-service
#          uri: lb://book-service
#          predicates: Path=/api/v1/authors
#        - id: book-service
#          uri: lb://book-service
#          predicates: Path=/api/v1/publishers
#        - id: book-service
#          uri: lb://book-service
#          predicates: Path=/api/v1/genres
server:
  port: 8083
eureka:
  client:
    service-url:
      default-zone: https://localhost:8761/eureka