spring:
  application:
    name: user-auth-service
  cache:
    type: redis
  redis:
    host: localhost
    port: 6379
server:
  port: 8084
eureka:
  client:
    service-url:
      default-zone: https://localhost:8761/eureka
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic