spring:
  application:
    name: user-registration-service
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
  jpa:
    show-sql: false
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        cache:
          use_query_cache: false

  liquibase:
    enabled: true
    change-log: db.changelog/db.changelog-master.yml
server:
  port: 8082
eureka:
  client:
    service-url:
      default-zone:
        https://localhost:8761/eureka
springfox:
  documentation:
    swagger-ui:
      enabled: true